version: '3.4'
services:
  development:
    build:
      context: .
      target: base
    restart: always
    ports:
      - '3000:3000'
      - '9228:9222'
    volumes:
      - .:/usr/src/app
    environment:
      TZ: 'Asia/Seoul'
      DB_HOST: 'docker.for.mac.localhost'
    command: [
      'node_modules/.bin/nodemon',
      '--ignore',
      'dist/',
      '--ext',
      'ts,js',
      '--exec',
      'npm run build && npm run debug'
    ]
