version: '3.4'
services:
  production:
    build:
      context: .
      target: production
    restart: always
    ports:
      - '3000:3000'
    environment:
      TZ: 'Asia/Seoul'
      DB_HOST: 'docker.for.mac.localhost'
    command: [
      'npm', 'start'
    ]
